import type { NextPage } from 'next';
import Head from 'next/head';

import First from './components/first';
import CadEmployee from './components/cadEmployee';

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-center">
      <Head>
        <title>Creative Festas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <First />
      <CadEmployee />
    </div>
  );
};

export default Home;
